### ISSUE TITLE
Chyt 2.16.0 return timestamp error

### ISSUE THREAD

**Issue by Arustinal** [ytsaurus/ytsaurus#933]
chyt 2.16.0

Select query that reads timestamps from dynamic ordered table

Error is "timestamp64" is not valid type_v3 simple type

UI shows query as completed, but Result has that error

**Comment by DimasKovas** [comment]
Hi @Arustinal.
It's a backward compatibility issue.

CHYT 2.16.0 supports a bunch of new data types. Now it saves a `DateTime64` ClickHouse value as a `timestampt64` YT value. Unfortunately, `timestamp64` has been introduced in a 24.1 YTsaurus release, so you get this `not a valid type` error because your YTsaurus version is older.

As a workaround, you can either update your YTsaurus version (the public announcement, change log and official docker images will be available in the nearest future), or downgrade a CHYT version to 2.14/2.15.

Anyway, I will add the note that CHYT 2.16 requires at least YTsaurus 24.1 to the release notes for now.

If this solution is not suitable for you and you need to use a new chyt version with older YTsaurus clusters - let us know, we will think about other workarounds here.

**Comment by Arustinal** [comment]
I am ok with downgrade chyt to 2.14, as 2.15 doesnt have published package. Waiting for 24.1 release.
